import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/header";
import Footer from "@/components/home/Footer";
import { LayoutProvider } from "@/context/LayoutContext";
import LayoutWrapper from "@/components/LayoutWrapper/LayoutWrapper";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LayoutProvider>
          <LayoutWrapper Header={Header} Footer={Footer}>
            {children}
          </LayoutWrapper>
        </LayoutProvider>
      </body>
    </html>
  );
}
